name: myr
channels:
  - conda-forge
dependencies:
  - r-base
  - r-processx
  - r-httpuv      # required by replr_server
  - r-jsonlite    # required by replr_server
  - r-httr
  - r-later
  - r-tibble
  - r-testthat      
  - requests

